### PR TITLE
Added Maven build script

### LINKED ISSUE #28: Building Tool
We need to implement a building tool not just a script for building. Building tool will be used within the CI as well.

### PR DESCRIPTION
**Pull request by Mohido**
A maven build script was added. It uses Java 11 compiler (Since we have some language specifications that was introduced in java 11 - var, for instance-). The standard Directory organizing is a bit difference: Standard is to have "src/main/java/" And ours is a more simplified version of that since we only have 1 project (1 module). Ours: "src_ragmad/ragmad/" and the rest of the source code files are there. Note that, no "mvn exec:java" exists on the meantime. If you want to run the project you need to package it first ("mvn package"), then "cd bin", after that, run the .jar file.

### CODE REVIEW

**Comment by RealGorandos** [comment]
I think @Shuaa11 mentioned she is using Junit 5 on the testing issue.

**Comment by Mohido** [comment]
> I think @Shuaa11 mentioned she is using Junit 5 on the testing issue.

Yes I think that is correct. Well I will re-edit that and pull request again.

**Comment by Mohido** [comment]
I think I will leave @Shuaa11  edit the Maven Junit version and dependency to what she prefers. 
@Shuaa11 can you do that?

**Review by RealGorandos — APPROVED** [review]
It can be merged and it looks fine

**Review by Shuaa11 — APPROVED** [review]
It looks good. Well done!

**Pull request merged**
